In [2]:
import numpy as np

# 创建数组对象

In [16]:
arr1 = np.array([1,2,3,4])                #创建一维数组
print("一维数组：",arr1)

一维数组： [1 2 3 4]


In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])        #创建二维2数组
print("二维数组：\n",arr2)

二维数组：
 [[1 2 3]
 [4 5 6]]


In [8]:
arr3 = np.array([1,2,3,4],ndmin=3)       #设置最小为度3
print("三维数组:\n",arr3)

三维数组:
 [[[1 2 3 4]]]


In [9]:
arr4 = np.array([1,2,3,4],dtype=complex) #指定数据类型dtype为复数
print("复数数组:",arr4)

复数数组: [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


# 数组的属性

In [15]:
arr1 = np.array([[1,2,3],[4,5,6]])
print("数组维度:",arr1.ndim)
print("数组形状:",arr1.shape)
print("数组的元素总数:",arr1.size)
print("数组元素的数据类型:",arr1.dtype)
print("数组中每个元素的大小：",arr1.itemsize)
arr1.shape=(3,2)  #shape属性应用
print("数组\n",arr1)
#利用dtype属性指定数据类型
arr3 = np.array([1,2,3,4],dtype = np.float32)
print("数组元素的数据类型:",arr3.dtype)

数组维度: 2
数组形状: (2, 3)
数组的元素总数: 6
数组元素的数据类型: int32
数组中每个元素的大小： 4
数组
 [[1 2]
 [3 4]
 [5 6]]
数组元素的数据类型: float32


In [25]:
pro_type = np.dtype([('pro_name',str,50),('pro_price',np.float32)])
print('数据类型：',pro_type)

数据类型： [('pro_name', '<U50'), ('pro_price', '<f4')]


In [27]:
pro_arr=np.array([('电视机',3400),('空调',2600)],dtype=pro_type)
print('自定义数据类型:',pro_arr)

自定义数据类型: [('电视机', 3400.) ('空调', 2600.)]


# 索引和切片

In [9]:
#创建一维数组
arr=np.array([1,2,6,8,9,10,12])
a=arr[4]                                #获取第5个元素
print(a)

9


In [5]:
#一维数组切片
b1=arr[1:6:2]             
b2=arr[:5]
b3=arr[2:]
print(b1,b2,b3)

[ 2  8 10] [1 2 6 8 9] [ 6  8  9 10 12]


In [8]:
#修改数组中的元素
arr[1:3]=20,30
print(arr)

[ 1 20 30  8  9 10 12]


In [10]:
#创建二维数组
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
a=arr[1,3]
print(a)

8


In [28]:
#二维数组切片
b1=arr[:2,1:3]
b2=arr[1:,2:5]
b3=arr[:2:2,:3:2]
b4=arr[...,1:3]
print('1:',b1)
print('2:',b2)
print('3:',b3)
print('4:',b4)

1: [[1 2]
 [6 7]]
2: [[7 8 9]]
3: [[0 2]]
4: [[1 2]
 [6 7]]


In [29]:
#修改数组中的元素
arr[:2:2,:3:2]=44,55
print(arr)

[[44  1 55  3  4]
 [ 5  6  7  8  9]]


In [38]:
#整数索引
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[(0,1,2),(0,1,0)]
print(b)           #[0,0],[1,1],[2,0]

[1 5 7]


In [40]:
b=a[(0,0,2,2),(0,2,0,2)]
print(b)           #[0,0],[0,2],[2,0],[2,2]

[1 3 7 9]


In [45]:
#布尔值索引
a=np.array([[0,1,2,],[3,4,5],[6,7,8],[9,10,11]])
print('a数组是：',a)
#生成大于6的元素组成数组
b=a[a>5]
print(b)

a数组是： [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 6  7  8  9 10 11]
