In [1]:
import numpy as np

# 创建数组对象

In [16]:
arr1 = np.array([1,2,3,4])                #创建一维数组
print("一维数组：",arr1)

一维数组： [1 2 3 4]


In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])        #创建二维2数组
print("二维数组：\n",arr2)

二维数组：
 [[1 2 3]
 [4 5 6]]


In [8]:
arr3 = np.array([1,2,3,4],ndmin=3)       #设置最小为度3
print("三维数组:\n",arr3)

三维数组:
 [[[1 2 3 4]]]


In [9]:
arr4 = np.array([1,2,3,4],dtype=complex) #指定数据类型dtype为复数
print("复数数组:",arr4)

复数数组: [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


# 数组的属性

In [15]:
arr1 = np.array([[1,2,3],[4,5,6]])
print("数组维度:",arr1.ndim)
print("数组形状:",arr1.shape)
print("数组的元素总数:",arr1.size)
print("数组元素的数据类型:",arr1.dtype)
print("数组中每个元素的大小：",arr1.itemsize)
arr1.shape=(3,2)  #shape属性应用
print("数组\n",arr1)
#利用dtype属性指定数据类型
arr3 = np.array([1,2,3,4],dtype = np.float32)
print("数组元素的数据类型:",arr3.dtype)

数组维度: 2
数组形状: (2, 3)
数组的元素总数: 6
数组元素的数据类型: int32
数组中每个元素的大小： 4
数组
 [[1 2]
 [3 4]
 [5 6]]
数组元素的数据类型: float32


In [25]:
pro_type = np.dtype([('pro_name',str,50),('pro_price',np.float32)])
print('数据类型：',pro_type)

数据类型： [('pro_name', '<U50'), ('pro_price', '<f4')]


In [27]:
pro_arr=np.array([('电视机',3400),('空调',2600)],dtype=pro_type)
print('自定义数据类型:',pro_arr)

自定义数据类型: [('电视机', 3400.) ('空调', 2600.)]


# 索引和切片

In [9]:
#创建一维数组
arr=np.array([1,2,6,8,9,10,12])
a=arr[4]                                #获取第5个元素
print(a)

9


In [5]:
#一维数组切片
b1=arr[1:6:2]             
b2=arr[:5]
b3=arr[2:]
print(b1,b2,b3)

[ 2  8 10] [1 2 6 8 9] [ 6  8  9 10 12]


In [8]:
#修改数组中的元素
arr[1:3]=20,30
print(arr)

[ 1 20 30  8  9 10 12]


In [10]:
#创建二维数组
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
a=arr[1,3]
print(a)

8


In [28]:
#二维数组切片
b1=arr[:2,1:3]
b2=arr[1:,2:5]
b3=arr[:2:2,:3:2]
b4=arr[...,1:3]
print('1:',b1)
print('2:',b2)
print('3:',b3)
print('4:',b4)

1: [[1 2]
 [6 7]]
2: [[7 8 9]]
3: [[0 2]]
4: [[1 2]
 [6 7]]


In [29]:
#修改数组中的元素
arr[:2:2,:3:2]=44,55
print(arr)

[[44  1 55  3  4]
 [ 5  6  7  8  9]]


In [38]:
#整数索引
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[(0,1,2),(0,1,0)]
print(b)           #[0,0],[1,1],[2,0]

[1 5 7]


In [40]:
b=a[(0,0,2,2),(0,2,0,2)]
print(b)           #[0,0],[0,2],[2,0],[2,2]

[1 3 7 9]


In [45]:
#布尔值索引
a=np.array([[0,1,2,],[3,4,5],[6,7,8],[9,10,11]])
print('a数组是：',a)
#生成大于6的元素组成数组
b=a[a>5]
print(b)

a数组是： [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 6  7  8  9 10 11]


# 修改数组形状

In [76]:
arr=np.array([[0,1,2,4],[5,6,7,8],[9,10,11,12]])
print(arr,arr.shape)

[[ 0  1  2  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [77]:
#通过维度属性修改数组形状
arr.shape=(4,3)
print(arr,arr.shape)

[[ 0  1  2]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [17]:
#reshape()函数（创建一个新数组）
arr_b=arr.reshape(2,6)
print(arr)
print(arr_b)

[[ 0  1  2]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 0  1  2  4  5  6]
 [ 7  8  9 10 11 12]]


In [73]:
arr=np.array([[0,1,2,4],[5,6,7,8],[9,10,11,12]])
print(arr,arr.shape)

[[ 0  1  2  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [75]:
#resize()函数  （修改原数组）
arr.resize(5,5)
arr

array([[ 0,  1,  2,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [74]:
a=np.resize(arr,(4,4))
a

array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 0,  1,  2,  4]])

# 数组的展平

In [79]:
import numpy as np

In [101]:
#ravel()函数 
arr=np.array([[0,1,2,4],[5,6,7,8],[9,10,11,12]])
arr_b=arr.ravel()
print(arr)
print(arr_b)

[[ 0  1  2  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 0  1  2  4  5  6  7  8  9 10 11 12]


In [100]:
arr.ravel()[2]=100
arr

array([[  0,   1, 100,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [102]:
arr_c=arr.ravel("F")
arr_c

array([ 0,  5,  9,  1,  6, 10,  2,  7, 11,  4,  8, 12])

In [99]:
arr.flatten()[2]=100
arr

array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
#flatten()函数
arr_c=arr.flatten()
print(arr,arr_c)

[[ 0  1  2  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] [ 0  1  2  4  5  6  7  8  9 10 11 12]


# 数组的转置和轴对换

In [130]:
import numpy as np
arr=np.arange(10).reshape(2,5)
print('原数组：',arr)

原数组： [[0 1 2 3 4]
 [5 6 7 8 9]]


In [129]:
#transpose()函数
print('转置数组')
print(np.transpose(arr))


转置数组
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [132]:
#ndarray.T函数
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [137]:
#rollaxis()函数
arr=np.arange(8).reshape(2,2,2)
print('原数组：',arr)
#将轴2滚动到轴0(宽度到深度)
print('----')
print(np.rollaxis(arr,2))

原数组： [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
----
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [138]:
print(np.rollaxis(arr,0,1))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [140]:
#用swapaxes()函数
arr=np.arange(8).reshape(2,2,2)
print('原数组',arr)
print('--------')
print(np.swapaxes(arr,0,2))

原数组 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
--------
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


# 数组的连接

In [1]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print('第一个数组')
print(arr1)
arr2=np.array([['a',8,9],['b',11,12]])
print('第二个数组')
print(arr2)

第一个数组
[[1 2 3]
 [4 5 6]]
第二个数组
[['a' '8' '9']
 ['b' '11' '12']]


In [9]:
#concatenate函数
print('沿0轴连接2个数组')
print(np.concatenate((arr1,arr2)))
print('沿1轴堆叠2个函数')
print(np.concatenate((arr1,arr2),1))

沿0轴连接2个数组
[['1' '2' '3']
 ['4' '5' '6']
 ['a' '8' '9']
 ['b' '11' '12']]
沿1轴堆叠2个函数
[['1' '2' '3' 'a' '8' '9']
 ['4' '5' '6' 'b' '11' '12']]


In [13]:
#stack函数
print('沿0轴堆叠2个数组')
print(np.stack((arr1,arr2),0))
print('沿轴1堆叠2个数组')
print(np.stack((arr1,arr2),1))

沿0轴堆叠2个数组
[[['1' '2' '3']
  ['4' '5' '6']]

 [['a' '8' '9']
  ['b' '11' '12']]]
沿轴1堆叠2个数组
[[['1' '2' '3']
  ['a' '8' '9']]

 [['4' '5' '6']
  ['b' '11' '12']]]


In [3]:
#hstack函数和vstack函数
print('水平堆叠')
print(np.hstack((arr1,arr2)))
print('竖直堆叠')
print(np.vstack((arr1,arr2)))

水平堆叠
[['1' '2' '3' 'a' '8' '9']
 ['4' '5' '6' 'b' '11' '12']]
竖直堆叠
[['1' '2' '3']
 ['4' '5' '6']
 ['a' '8' '9']
 ['b' '11' '12']]


# 数组的分割

In [4]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print('第1个数组arr1:',arr1)
arr2=np.arange(9)
print('第2个数组arr2:',arr2)

第1个数组arr1: [[1 2 3]
 [4 5 6]]
第2个数组arr2: [0 1 2 3 4 5 6 7 8]


In [12]:
#使用split函数
print('将arr1数组竖直分割为2个大小相等的子数组:')
print(np.split(arr1,2,axis=0))
print('将arr1数组水平分割为3个大小相等的子数组:')
print(np.split(arr1,3,axis=1))
print('将arr2数组在一维数组中表明位置分割:')
print(np.split(arr2,[2,5]))

将arr1数组竖直分割为2个大小相等的子数组:
[array([[1, 2, 3]]), array([[4, 5, 6]])]
将arr1数组水平分割为3个大小相等的子数组:
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
将arr2数组在一维数组中表明位置分割:
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8])]


In [14]:
#使用hsplit函数和vsplit函数
print('arr1数组水平分割:')
print(np.hsplit(arr1,3))
print('arr1数组竖直分割')
print(np.vsplit(arr1,2))
print('arr2数组水平分割')
print('np.hsplit(arr2,[2,5])')

arr1数组水平分割:
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
arr1数组竖直分割
[array([[1, 2, 3]]), array([[4, 5, 6]])]
arr2数组水平分割
np.hsplit(arr2,[2,5])


# 数组转换

In [2]:
#数组转换成列表
import numpy as np
arr=np.arange(9).reshape(3,3)
print('原数组',arr)

原数组 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
print('将arr数组转换成列表')
arr_list=arr.tolist()
print(arr_list)

将arr数组转换成列表
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


# 添加/删除数组元素

In [7]:
#append函数
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print('第一个数组arr：',arr)

第一个数组arr： [[1 2 3 4]
 [5 6 7 8]]


In [13]:
print('向第一个数组添加元素：')
print(np.append(arr,[[9,10],[11,12]]))
print('原数组:',arr)

向第一个数组添加元素：
[ 1  2  3  4  5  6  7  8  9 10 11 12]
原数组: [[1 2 3 4]
 [5 6 7 8]]


In [15]:
print('沿0轴添加数组:')
print(np.append(arr,[[9,10,11,12],[11,11,11,11]],axis=0))

沿0轴添加数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [11 11 11 11]]


In [17]:
print('沿1轴添加数组:')
print(np.append(arr,[[9,10],[11,12]],1))

沿1轴添加数组:
[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]


In [18]:
#insert函数
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print('第一个数组arr:',arr)

第一个数组arr: [[1 2 3 4]
 [5 6 7 8]]


In [20]:
print('未传递axis参数，在插入前输入数组会被展开。')
print(np.insert(arr,4,[9,10,11,12]))

未传递axis参数，在插入前输入数组会被展开。
[ 1  2  3  4  9 10 11 12  5  6  7  8]


In [21]:
print('传递了axis参数，会以广播值数组来匹配数组。')
print('沿0轴广播:')
print(np.insert(arr,2,[9],axis=0))

传递了axis参数，会以广播值数组来匹配数组。
沿0轴广播:
[[1 2 3 4]
 [5 6 7 8]
 [9 9 9 9]]


In [22]:
print('沿0轴插入:')
print(np.insert(arr,2,[9,10,11,12],axis=0))

沿0轴插入:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print('沿1轴广播:')
print(np.insert(arr,2,[[9],[10]],axis=1))

沿1轴广播:
[[ 1  2  9 10  3  4]
 [ 5  6  9 10  7  8]]


In [24]:
print('沿1轴广播:')
print(np.insert(arr,2,[[9,10],[11,12]],axis=1))

沿1轴广播:
[[ 1  2  9 11  3  4]
 [ 5  6 10 12  7  8]]


In [25]:
#delete()函数
import numpy as np
arr = np.arange(16).reshape(4,4)
print('第一个数组arr:',arr)

第一个数组arr: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
print('若未传递axis参数，在删除前输入数组会被展开。')
print(np.delete(arr,[6,9,12]))
print(arr)

若未传递axis参数，在删除前输入数组会被展开。
[ 0  1  2  3  4  5  7  8 10 11 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [29]:
print('删除第3列')
print(np.delete(arr,2,1))

删除第3列
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]
 [12 13 15]]


In [30]:
print('删除第二行')
print(np.delete(arr,1,0))

删除第二行
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
print('从数组中删除用切片表示元素范围值：')
print(np.delete(arr,::2))
print(np.delete(arr,s_[::2]))

SyntaxError: invalid syntax (Temp/ipykernel_18492/2079963770.py, line 2)

In [37]:
print(np.s_[::2])
print()

slice(None, None, 2)
